allowBuilds:
  '@swc/core': true
  bcrypt: true
  better-sqlite3: true
  bufferutil: true
  esbuild: true
  pnpm: true
  scramjet-root@https://github.com/MercuryWorkshop/scramjet/archive/refs/tags/latest.tar.gz: true
